# Generated by Django 5.0.2 on 2024-03-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_film_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='img',
            field=models.CharField(max_length=500),
        ),
    ]
