# Generated by Django 5.0.2 on 2024-03-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_alter_film_premier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='title',
        ),
    ]
